title: CV | Timur BERK
description:  Timur Berk özgeçmiş bilgileri.
url: https://cv.timurberk.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
